-- V1 — initial schema (PostgreSQL).
--
-- On any existing production database this is BASELINED (treated as
-- already applied) by Flyway because spring.flyway.baseline-on-migrate=true.
-- On a fresh database (Supabase initial provisioning, local dev, CI) this
-- file creates the full schema from scratch. CREATE TABLE IF NOT EXISTS
-- keeps it idempotent.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NULL,
    salary INTEGER NULL,
    phone VARCHAR(255) NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    oauth_user BOOLEAN NOT NULL DEFAULT FALSE,
    password_set BOOLEAN NOT NULL DEFAULT FALSE,
    provider VARCHAR(255) NOT NULL,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    category VARCHAR(50) NULL,
    type VARCHAR(10) NOT NULL,
    description VARCHAR(255) NULL,
    transaction_date DATE NOT NULL,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    period VARCHAR(20) NOT NULL,
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_insights_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    email VARCHAR(255) NULL,
    ip VARCHAR(255) NULL,
    user_agent VARCHAR(255) NULL,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    "timestamp" TIMESTAMP(6) NULL
);

CREATE INDEX IF NOT EXISTS idx_login_history_user_id ON login_history(user_id);

CREATE TABLE IF NOT EXISTS otp_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_otp_codes_email ON otp_codes(email);
