-- V2 — password-reset token table introduced by Phase 1 / Step 5.
--
-- Stores SHA-256(token) only; the raw token is sent via email exactly once
-- and never persisted server-side. Tokens are single-use, expire in
-- "password.reset.ttl-minutes" (default 30).

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_prt_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_prt_user ON password_reset_tokens(user_id);
